#!/bin/sh

# To be used as custom command (instead of default shell) in terminal emulator profile.
# Not suitable for default profile as it will not work with '-e' (execute).

# If tmux is not running, start tmux.
# If tmux is running and no session is attached, attach session.
# If tmux is running and session is attached, start shell.

# Usage: create new profile (named e.g. "tmux") and set this script as its 'custom command'.
# Start terminal emulator with this profile - e.g. roxterm -p tmux

export TERM=xterm-256color

sessions="$(tmux ls)"
if [ "$?" -eq 0 ]; then
  case "$sessions" in
    *attached*)
      exec /bin/bash ;;
    *)
      exec tmux attach ;;
  esac
else
  exec tmux
fi
