#!/bin/sh

# To be used as custom command (instead of default shell) in terminal emulator profile.
# Not suitable for default profile as it will not work with '-e' (execute).

# If tmux is not running, start tmux.
# If tmux is running and no session is attached, attach session.
# If tmux is running and session is attached, start shell.

# Usage: create new profile (named e.g. "tmux") and set this script as its 'custom command'.
# Start terminal emulator with this profile - e.g. roxterm -p tmux

SESSION_NAME="${1:-0}"

export TERM=xterm-256color
USER_SHELL="$(getent passwd "$(id -u)")"
USER_SHELL="${USER_SHELL##*:}"

session="$(tmux ls | \
  while read line; do case "$line" in ${SESSION_NAME}:*) echo "$line"; break ;; esac; done)"

case "$session" in
  ${SESSION_NAME}:*attached*)
    exec "$USER_SHELL" ;;
  ${SESSION_NAME}:*)
    exec tmux attach-session -t "$SESSION_NAME" ;;
  *)
    exec tmux new-session -s "$SESSION_NAME" ;;
esac
